### ISSUE TITLE
The "find_next_system" command works inconsistently

### ISSUE THREAD

**Issue by Smiffleblurf** [Stickymaddness/Sextant#8]
Just wanted to first say a huge thank you for making this plugin tool. When I ran across your post on ED's forums while looking for a VR typing solution for doing Road to Riches I was happy to see someone attempt to make this already long torturous process more tolerable in VR.

Everything is setup and working fine. All the commands work consistently well for me except for "find_next_system". Sometimes when I say it nothing will happen. Another time it will get as far as moving the UI tab over, but doesn't paste in the data. Then when I tried to time what it was doing I moved the tab over and highlighted the text field at the right time for the script to paste it in to get it to work made me think it was a timing issue perhaps.

I am wondering if perhaps fiddling with the delays in the Settings.json might resolve this or figuring out what is causing this not to work consistently? I'm curious what I can tweak?

I also don't mind going to the galaxy menu myself, highlighting the text field and then saying "enter_next_system" and it'll just paste the next system in as an alternative input option.

Again thanks for your work on this! 🥇

**Comment by Stickymaddness** [comment]
Glad to hear you've found Sextant so useful!

You mention sometimes when you say "find_next_system" nothing happens, do you at least hear Sextant replying "Finding next system..." if not, in those cases it might mean that VoiceAttack is not understanding your voice command.

For the times when Sextant will intermittently get as far as moving the UI tab, tweaking the settings can help this. It's difficult for me to debug because it's dependent on system setup and on my setup I don't have any issues.

You can tweak the settings however you like, you could try increase `GalaxyMapOpenDelay` so that there's a longer delay between opening the galaxy map and when Sextant moves to the next tab `GalaxyMapUINavigateDelay` is the same concept but between tabs in the galaxy map. Lastly, `KeyDownDuration` is how long Sextant "presses" the keys down before releasing them.

A poster on the forum was able to get it working reliably on their system with the following changes, which could be a good starting point:

```
"GalaxyMapOpenDelay": "2000",
"GalaxyMapUINavigateDelay": "500",
"KeyDownDuration": 20 
```

Let me know if you manage to get it more reliable, and with what settings.
